import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get('window');

export const postItemStyles = StyleSheet.create({
  postContainer: {
    backgroundColor: "#ffffff",
    marginHorizontal: 0,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    elevation: 2,
    position: 'relative',
    overflow: 'visible', 
  },
  postHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    paddingBottom: 12,
    position: 'relative',
  },
  userInfo: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#98DB52",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    overflow: 'hidden',
  },
  avatarImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  avatarText: {
    color: "#ffffff",
    fontWeight: "bold",
    fontSize: 16,
  },
  userDetails: {
    flex: 1,
  },
  name: {
    fontSize: 15,
    fontWeight: "600",
    color: "#14171a",
    marginBottom: 2,
  },
  username: {
    fontSize: 15,
    fontWeight: "600",
    color: "#14171a",
    marginBottom: 2,
  },
  communityName: {
    fontSize: 13,
    fontWeight: "600",
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "#E8F5FD",
    borderRadius: 16,
    overflow: "hidden",
    alignSelf: "flex-start",
    marginLeft: 16,
    marginTop: 12,
    marginBottom: 8,
  },
  adminBadge: {
    backgroundColor: "#FEE",
  },
  timestamp: {
    fontSize: 13,
    color: "#657786",
  },
  moreButton: {
    padding: 8,
    borderRadius: 20,
    position: 'relative',
  },
  moreText: {
    fontSize: 18,
    color: "#657786",
    fontWeight: "bold",
  },
  dropdownOverlay: {
    position: 'absolute',
    top: -16,
    left: -16,
    right: -16,
    bottom: -1000,
    backgroundColor: 'transparent',
    zIndex: 998,
  },
  dropdownMenu: {
    position: 'absolute',
    top: 40,
    right: 8, 
    backgroundColor: '#ffffff',
    borderRadius: 12,
    paddingVertical: 8,
    minWidth: 140,
    maxWidth: 180, 
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 8,
    zIndex: 999,
    borderWidth: 1,
    borderColor: '#e1e8ed',
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12, 
    paddingVertical: 10,
  },
  deleteItem: {
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  dropdownIcon: {
    fontSize: 16,
    marginRight: 10, 
    width: 20, 
  },
  dropdownText: {
    fontSize: 14, 
    color: '#14171a',
    fontWeight: '500',
    flex: 1, 
  },
  deleteText: {
    color: '#e53e3e',
  },
  postContent: {
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  postTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#14171a",
    marginBottom: 8,
    lineHeight: 22,
  },
  postCaption: {
    fontSize: 15,
    color: "#14171a",
    lineHeight: 20,
  },
  imageContainer: {
    marginBottom: 12,
  },
  singleImage: {
    width: width,
    height: width * 0.75, 
    backgroundColor: "#f0f0f0",
  },
  imageList: {
    paddingLeft: 16,
  },
  multipleImage: {
    width: width * 0.7,
    height: width * 0.5,
    borderRadius: 12,
    marginRight: 12,
    backgroundColor: "#f0f0f0",
  },
  actionBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 0.5,
    borderTopColor: "#e1e8ed",
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 32,
    paddingVertical: 4,
  },
  viewPostButton: {
    backgroundColor: "#98DB52",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginLeft: "auto",
  },
  viewPostText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "600",
  },
  actionIcon: {
    fontSize: 18,
    marginRight: 6,
  },
  actionText: {
    fontSize: 13,
    color: "#657786",
    fontWeight: "500",
  },
  likedIcon: {
    transform: [{ scale: 1.1 }],
  },
  likedText: {
    color: "#e91e63",
    fontWeight: "600",
  },
});