import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

export const reactionGame = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#111827",
  },
  gradient: {
    flex: 1,
    backgroundColor: "#1F2937",
  },
  scrollContent: {
    flexGrow: 1,
    padding: 20,
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 24,
    gap: 12,
  },
  statBox: {
    flex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  statLabel: {
    fontSize: 12,
    color: "#9CA3AF",
    marginBottom: 4,
    fontWeight: "600",
  },
  statValue: {
    fontSize: 24,
    color: "#FFFFFF",
    fontWeight: "bold",
  },
  gameAreaWrapper: {
    marginBottom: 24,
  },
  gameAreaAnimated: {
    width: "100%",
  },
  gameArea: {
    width: "100%",
    height: height * 0.4,
    borderRadius: 24,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.44,
    shadowRadius: 10.32,
    elevation: 16,
  },
  instructionText: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginTop: 20,
    textAlign: "center",
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  feedbackText: {
    fontSize: 20,
    color: "#FFFFFF",
    marginTop: 12,
    fontWeight: "600",
    opacity: 0.9,
  },
  tooEarlyText: {
    fontSize: 16,
    color: "#FFFFFF",
    marginTop: 8,
    opacity: 0.9,
  },
  instructionsBox: {
    backgroundColor: "rgba(59, 130, 246, 0.15)",
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(59, 130, 246, 0.3)",
  },
  instructionsTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#3B82F6",
    marginBottom: 12,
  },
  instructionsText: {
    fontSize: 14,
    color: "#D1D5DB",
    lineHeight: 22,
  },
  resetButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(239, 68, 68, 0.2)",
    borderRadius: 12,
    padding: 14,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.4)",
    gap: 8,
  },
  resetButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  recordsContainer: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  recordsTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 12,
  },
  recordsList: {
    gap: 8,
  },
  recordItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 10,
    padding: 12,
    gap: 12,
  },
  recordNumber: {
    fontSize: 14,
    color: "#9CA3AF",
    fontWeight: "600",
    width: 30,
  },
  recordTime: {
    flex: 1,
    fontSize: 16,
    color: "#FFFFFF",
    fontWeight: "600",
  },
  leaderboardButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(168, 85, 247, 0.2)",
    borderRadius: 12,
    padding: 14,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(168, 85, 247, 0.4)",
    gap: 8,
  },
  leaderboardButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  leaderboardContainer: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  leaderboardTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 16,
    textAlign: "center",
  },
  leaderboardItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    gap: 12,
  },
  leaderboardRank: {
    width: 32,
    alignItems: "center",
  },
  rankText: {
    fontSize: 16,
    color: "#9CA3AF",
    fontWeight: "bold",
  },
  leaderboardName: {
    flex: 1,
    fontSize: 16,
    color: "#FFFFFF",
    fontWeight: "600",
  },
  leaderboardTime: {
    fontSize: 16,
    color: "#10B981",
    fontWeight: "bold",
  },
  noDataText: {
    textAlign: "center",
    color: "#9CA3AF",
    fontSize: 14,
    fontStyle: "italic",
    paddingVertical: 20,
  },
});