export const PRODUCT_OPTIONS = [
  { label: "Helmet", value: "Helmet" },
  { label: "Riding Gloves", value: "Riding Gloves" },
  { label: "Jacket", value: "Jacket" },
  { label: "Windbreaker", value: "Windbreaker" },
  { label: "Pants", value: "Pants" },
  { label: "Boots", value: "Boots" },
  { label: "Rain Gear", value: "Rain Gear" },
  { label: "Motor Oil", value: "Motor Oil" },
  { label: "Brake Pads", value: "Brake Pads" },
  { label: "Tires", value: "Tires" },
  { label: "Wheels", value: "Wheels" },
  { label: "Exhaust", value: "Exhaust" },
  { label: "Chain & Sprockets", value: "Chain & Sprockets" },
  { label: "Spark Plugs", value: "Spark Plugs" },
  { label: "Air Filter", value: "Air Filter" },
  { label: "Oil Filter", value: "Oil Filter" },
  { label: "Battery", value: "Battery" },
  { label: "LED Lights", value: "LED Lights" },
  { label: "Horn", value: "Horn" },
  { label: "Mirrors", value: "Mirrors" },
  { label: "Seats", value: "Seats" },
  { label: "Phone Mount", value: "Phone Mount" },
  { label: "Tank Bag", value: "Tank Bag" },
  { label: "Saddlebags", value: "Saddlebags" },
  { label: "Top Box", value: "Top Box" },
  { label: "Decals & Stickers", value: "Decals & Stickers" },
  { label: "Motorcycle Cover", value: "Motorcycle Cover" },
  { label: "Tools & Maintenance Kits", value: "Tools & Maintenance Kits" },
  { label: "Action Camera Mounts", value: "Action Camera Mounts" },
  { label: "GPS Devices", value: "GPS Devices" },
  { label: "Security Lock/Disc Lock", value: "Security Lock/Disc Lock" },
  { label: "Intercom System", value: "Intercom System" },
  { label: "Others", value: "Others" },
];

export const SERVICE_OPTIONS = [
  { label: "Change Oil", value: "Change Oil" },
  { label: "Brake Inspection", value: "Brake Inspection" },
  { label: "Tire Replacement", value: "Tire Replacement" },
  { label: "Battery Replacement", value: "Battery Replacement" },
  { label: "Chain Adjustment", value: "Chain Adjustment" },
  { label: "Tune-Up", value: "Tune-Up" },
  { label: "Engine Check-Up", value: "Engine Check-Up" },
  { label: "Electrical Check", value: "Electrical Check" },
  { label: "Wiring Installation", value: "Wiring Installation" },
  { label: "Full Service", value: "Full Service" },
  { label: "Wheel Alignment", value: "Wheel Alignment" },
  { label: "Wash & Detailing", value: "Wash & Detailing" },
  { label: "Valve Adjustment", value: "Valve Adjustment" },
  { label: "Fuel System Cleaning", value: "Fuel System Cleaning" },
  { label: "Spark Plug Replacement", value: "Spark Plug Replacement" },
  { label: "Suspension Check", value: "Suspension Check" },
  { label: "Clutch Adjustment", value: "Clutch Adjustment" },
  { label: "Air Filter Replacement", value: "Air Filter Replacement" },
  { label: "Diagnostic Service", value: "Diagnostic Service" },
  { label: "On-call Mechanic", value: "On-call Mechanic" },
  { label: "Towing Assistance", value: "Towing Assistance" },
  { label: "Others", value: "Others" },
];
